from pydantic import BaseModel
import hashlib
import re


class SignatureBundle(BaseModel):
    yara: str | None
    sigma: str | None
    snort: str | None


class AttackEvent(BaseModel):
    log_id: int
    attack_type: str
    source_ip: str
    payload: str


def generate_signatures(event: AttackEvent) -> SignatureBundle:
    if not event.payload:
        return SignatureBundle(yara=None, sigma=None, snort=None)

    payload_hash = hashlib.sha256(event.payload.encode()).hexdigest()
    substrings = re.findall(r"[\w\-@./#&+=]{4,}", event.payload)
    unique_substrings = sorted(list(set(substrings)), key=len, reverse=True)[:5]

    if not unique_substrings:
        return SignatureBundle(yara=None, sigma=None, snort=None)

    # Generate YARA rule
    yara_rule = f"""rule PhantomNet_{{payload_hash[:8]}} {{
  meta:
    description = "Autogenerated by PhantomNet"
    hash = "{payload_hash}"
  strings:
"""
    for i, sub in enumerate(unique_substrings):
        yara_rule += f'    $s{i+1} = "{sub}"\n'
    yara_rule += """  condition:
    all of them
}"""

    # Generate Sigma rule
    sigma_rule = f"""title: PhantomNet Auto Rule {payload_hash[:8]}
status: experimental
logsource:
  category: network
detection:
  selection:
    payload_contains:
"""
    for sub in unique_substrings:
        sigma_rule += f'      - "{sub}"\n'
    sigma_rule += "  condition: selection" ""

    return SignatureBundle(yara=yara_rule, sigma=sigma_rule, snort=None)
