# backend_api/gateway_service/agent_api.py
import json
import os
import secrets
import asyncio
import hashlib
import datetime
from datetime import datetime
from typing import Optional, List, Dict, Any

from fastapi import (
    APIRouter,
    Depends,
    HTTPException,
    WebSocket,
    WebSocketDisconnect,
    Request,
    Header,
    status
)
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, update
from cryptography import x509
from cryptography.hazmat.primitives import serialization

from backend_api.core_config import SAFE_MODE
from backend_api.shared.database import get_db, Agent, AgentCredential, User
from backend_api.shared.schemas import (
    AgentRegistration,
    AgentHeartbeat,
    GossipMessage,
    BootstrapToken,
    SecurityEvent,
    AgentConfiguration
)
from backend_api.shared.security_utils import (
    generate_key_pair,
    sign_certificate,
    verify_inter_node_jwt,
    sign_data,
    verify_signature,
    generate_self_signed_ca,
)
from backend_api.shared.crl_utils import is_certificate_revoked, revoke_certificate
from backend_api.shared.message_bus import message_bus
from backend_api.shared.telemetry_ingest import TelemetryIngestService, TelemetryIngestConfig
from backend_api.iam_service.auth_methods import get_current_user, UserRole, has_role
from backend_api.core.logging import logger as pn_logger
from backend_api.core.response import success_response, error_response

router = APIRouter(tags=["Agents"])

# --- Setup Shared Services ---
TELEMETRY_INGESTOR_URL = os.getenv("TELEMETRY_INGESTOR_URL", "http://telemetry-ingestor:8000/ingest")
ca_key, ca_cert = generate_self_signed_ca()
bootstrap_tokens = {} # In-memory for now as per original code

# --- Telemetry Mock Broadcaster ---
async def mock_websocket_broadcaster(data: dict):
    pn_logger.debug(f"WS Broadcast: {data}")
    await message_bus.publish("websocket_broadcasts", data)

# Placeholder for real event processor - in a full app, this would be a singleton
telemetry_ingest_service_instance = TelemetryIngestService(
    raw_event_queue=asyncio.Queue(), 
    config=TelemetryIngestConfig()
)

@router.post("/agents/bootstrap-token")
async def create_bootstrap_token(current_user: User = Depends(has_role([UserRole.ADMIN]))):
    """Generates a single-use bootstrap token."""
    token = secrets.token_hex(32)
    expiration = datetime.utcnow().timestamp() + 300
    bootstrap_tokens[token] = expiration
    pn_logger.info(f"Bootstrap token generated by {current_user.username}")
    return success_response(data={"bootstrap_token": token, "expires_in": 300})

@router.post("/agents/register")
async def register_agent(agent_data: AgentRegistration, db: AsyncSession = Depends(get_db)):
    """Registers a new agent and issues a certificate."""
    # Bootstrap token validation (simplified for registration)
    if agent_data.bootstrap_token:
        # Check against in-memory store
        exp = bootstrap_tokens.get(agent_data.bootstrap_token)
        if not exp or datetime.utcnow().timestamp() > exp:
            return error_response(code="INVALID_TOKEN", message="Invalid or expired bootstrap token", status_code=401)
        # Token is one-time use
        del bootstrap_tokens[agent_data.bootstrap_token]

    private_key_pem, public_key_pem = generate_key_pair()
    signed_cert_pem = sign_certificate(
        public_key_pem=public_key_pem,
        ca_private_key_pem=ca_key.decode("utf-8"),
        ca_certificate_pem=ca_cert.decode("utf-8"),
        common_name=f"agent-{agent_data.public_key[:10]}",
    )

    signed_cert = x509.load_pem_x509_certificate(signed_cert_pem.encode("utf-8"))
    public_key_bytes = signed_cert.public_key().public_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PublicFormat.SubjectPublicKeyInfo,
    )
    fingerprint = hashlib.sha256(public_key_bytes).hexdigest()

    new_agent = Agent(
        public_key=public_key_pem,
        public_key_fingerprint=fingerprint,
        cert_serial=str(signed_cert.serial_number),
        role=agent_data.role,
        version=agent_data.version,
        location=agent_data.location,
        status="online",
        last_seen=datetime.utcnow(),
        quarantined=True,
        configuration=agent_data.configuration.model_dump_json() if agent_data.configuration else None,
        os=agent_data.os,
        capabilities=json.dumps(agent_data.capabilities) if agent_data.capabilities else None,
        self_healing_enabled=agent_data.self_healing_enabled or False,
        safe_mode_active=agent_data.safe_mode_active or False,
    )
    db.add(new_agent)
    await db.flush()

    agent_credential = AgentCredential(
        agent_id=new_agent.id, 
        public_key_pem=public_key_pem
    )
    db.add(agent_credential)
    await db.commit()

    pn_logger.info(f"Agent registered: {new_agent.id} (OS: {new_agent.os})")
    
    return success_response(data={
        "agent_id": new_agent.id,
        "certificate": signed_cert_pem
    })

@router.post("/agents/{agent_id}/heartbeat")
async def agent_heartbeat(
    agent_id: int, 
    heartbeat: AgentHeartbeat, 
    request: Request,
    db: AsyncSession = Depends(get_db)
):
    """Processes an agent heartbeat and updates status."""
    stmt = select(Agent).where(Agent.id == agent_id)
    result = await db.execute(stmt)
    agent = result.scalar_one_or_none()
    
    if not agent:
        return error_response(code="AGENT_NOT_FOUND", message="Agent not found", status_code=404)

    # CRL Check
    if await is_certificate_revoked(db, agent.cert_serial):
        pn_logger.warning(f"Heartbeat rejected for revoked agent {agent_id}")
        return error_response(code="CERTIFICATE_REVOKED", message="Certificate has been revoked", status_code=403)

    agent.status = heartbeat.status
    agent.last_seen = datetime.utcnow()
    if heartbeat.os: agent.os = heartbeat.os
    if heartbeat.capabilities: agent.capabilities = json.dumps(heartbeat.capabilities)
    if heartbeat.health_metrics: agent.last_reported_health = json.dumps(heartbeat.health_metrics)
    if heartbeat.recent_errors: agent.last_reported_errors = json.dumps(heartbeat.recent_errors)
    if heartbeat.self_healing_active is not None: agent.self_healing_enabled = heartbeat.self_healing_active
    if heartbeat.safe_mode_active is not None: agent.safe_mode_active = heartbeat.safe_mode_active
    
    await db.commit()

    # Telemetry Ingestion
    try:
        await telemetry_ingest_service_instance.ingest_raw_log(
            log_entry=heartbeat.model_dump(),
            source="agent_heartbeat",
            agent_id=str(agent.id),
            agent_os=agent.os,
            agent_capabilities=heartbeat.capabilities
        )
    except Exception as e:
        pn_logger.error(f"Failed to ingest heartbeat for agent {agent_id}: {str(e)}")

    return success_response(data={"status": "confirmed"})

@router.get("/agents/{agent_id}/config")
async def get_agent_config(agent_id: int, db: AsyncSession = Depends(get_db)):
    """Retrieves configuration for a specific agent."""
    stmt = select(Agent).where(Agent.id == agent_id)
    result = await db.execute(stmt)
    agent = result.scalar_one_or_none()
    
    if not agent:
        return error_response(code="NOT_FOUND", message="Agent not found", status_code=404)
    
    config_data = json.loads(agent.configuration) if agent.configuration else {}
    return success_response(data=config_data)

@router.get("/agents")
async def list_agents(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Lists all agents."""
    stmt = select(Agent)
    result = await db.execute(stmt)
    agents = result.scalars().all()
    return success_response(data=[{
        "id": a.id,
        "status": a.status,
        "os": a.os,
        "location": a.location,
        "version": a.version,
        "quarantined": a.quarantined
    } for a in agents])

@router.post("/agents/{agent_id}/approve")
async def approve_agent(
    agent_id: int, 
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(has_role([UserRole.ADMIN]))
):
    """Approves an agent from quarantine."""
    stmt = select(Agent).where(Agent.id == agent_id)
    result = await db.execute(stmt)
    agent = result.scalar_one_or_none()
    
    if not agent:
        return error_response(code="NOT_FOUND", message="Agent not found", status_code=404)

    agent.quarantined = False
    await db.commit()
    pn_logger.info(f"Agent {agent_id} approved by {current_user.username}")
    return success_response(data={"message": f"Agent {agent_id} approved."})

@router.websocket("/ws/agent-events")
async def websocket_agent_events(websocket: WebSocket):
    await websocket.accept()
    pubsub = message_bus.subscribe("agent-events")

    try:
        while True:
            # message_bus.get_message is likely synchronous/blocking. 
            # In a production setup, this would use an async pubsub.
            message = pubsub.get_message()
            if message and message["type"] == "message":
                await websocket.send_text(message["data"])
            await asyncio.sleep(0.1)
    except WebSocketDisconnect:
        pubsub.close()
