"""Initial migration

Revision ID: 42c6bdf3e26f
Revises: 
Create Date: 2025-12-17 17:48:18.704839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42c6bdf3e26f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('source_ip', sa.String(), nullable=True),
    sa.Column('host_identifier', sa.String(), nullable=True),
    sa.Column('raw_log_data', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_id'), 'audit_logs', ['event_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_host_identifier'), 'audit_logs', ['host_identifier'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource'), 'audit_logs', ['resource'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('soar_playbooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('trigger', sa.JSON(), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_soar_playbooks_id'), 'soar_playbooks', ['id'], unique=False)
    op.create_table('soar_playbook_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('playbook_id', sa.Integer(), nullable=False),
    sa.Column('playbook_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('triggered_by', sa.JSON(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('current_context', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['playbook_id'], ['soar_playbooks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('soar_playbook_execution_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('playbook_run_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('step_action', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['playbook_run_id'], ['soar_playbook_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_soar_playbook_execution_logs_id'), 'soar_playbook_execution_logs', ['id'], unique=False)
    op.add_column('agents', sa.Column('os', sa.String(), nullable=True))
    op.add_column('agents', sa.Column('capabilities', sa.JSON(), nullable=True))
    op.add_column('agents', sa.Column('last_reported_health', sa.JSON(), nullable=True))
    op.add_column('agents', sa.Column('last_reported_errors', sa.JSON(), nullable=True))
    op.add_column('agents', sa.Column('available_patches', sa.JSON(), nullable=True))
    op.add_column('agents', sa.Column('last_patch_applied', sa.DateTime(), nullable=True))
    op.add_column('agents', sa.Column('self_healing_enabled', sa.Boolean(), nullable=True))
    op.add_column('agents', sa.Column('safe_mode_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'safe_mode_active')
    op.drop_column('agents', 'self_healing_enabled')
    op.drop_column('agents', 'last_patch_applied')
    op.drop_column('agents', 'available_patches')
    op.drop_column('agents', 'last_reported_errors')
    op.drop_column('agents', 'last_reported_health')
    op.drop_column('agents', 'capabilities')
    op.drop_column('agents', 'os')
    op.drop_index(op.f('ix_soar_playbook_execution_logs_id'), table_name='soar_playbook_execution_logs')
    op.drop_table('soar_playbook_execution_logs')
    op.drop_table('soar_playbook_runs')
    op.drop_index(op.f('ix_soar_playbooks_id'), table_name='soar_playbooks')
    op.drop_table('soar_playbooks')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_host_identifier'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
